package dash

var states = []struct{
   code string
   example []string
}{
   {
      code: "Period.duration != nil",
      example: []string{
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "hulu.mpd",
         "itv.mpd",
         "max.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "roku.mpd",
         "rtbf.mpd",
      },
   },
   {
      code: "Period.duration == nil",
      example: []string{
         "amc.mpd",
         "draken.mpd",
         "kanopy.mpd",
         "plex.mpd",
         "pluto.mpd",
         "rakuten.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "Representation.SegmentBase != nil",
      example: []string{
         "hulu.mpd",
         "max.mpd",
         "rakuten.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "Representation.SegmentList != nil",
      example: []string{
         "criterion.mpd",
      },
   },
   {
      code: "Representation.SegmentTemplate != nil",
      example: []string{
         "amc.mpd",
         "canal.mpd",
         "cineMember.mpd",
         "ctv.mpd",
         "draken.mpd",
         "itv.mpd",
         "kanopy.mpd",
         "max.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "pluto.mpd",
         "roku.mpd",
         "rtbf.mpd",
      },
   },
   {
      code: "SegmentTemplate.SegmentTimeline != nil",
      example: []string{
         "amc.mpd",
         "canal.mpd",
         "cineMember.mpd",
         "ctv.mpd",
         "itv.mpd",
         "kanopy.mpd",
         "max.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "pluto.mpd",
         "roku.mpd",
         "rtbf.mpd",
      },
   },
   {
      code: "SegmentTemplate.SegmentTimeline == nil",
      example: []string{
         "criterion.mpd",
         "draken.mpd",
         "hulu.mpd",
         "molotov.mpd",
         "rakuten.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "SegmentTemplate.duration >= 1",
      example: []string{
         "amc.mpd",
         "criterion.mpd",
         "draken.mpd",
         "kanopy.mpd",
         "max.mpd",
         "molotov.mpd",
         "nbc.mpd",
         "paramount.mpd",
      },
   },
   {
      code: "SegmentTemplate.duration == 0",
      example: []string{
         "canal.mpd",
         "cineMember.mpd",
         "ctv.mpd",
         "hulu.mpd",
         "itv.mpd",
         "mubi.mpd",
         "plex.mpd",
         "pluto.mpd",
         "rakuten.mpd",
         "roku.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "SegmentTemplate.endNumber >= 1",
      example: []string{
         "molotov.mpd",
      },
   },
   {
      code: "SegmentTemplate.endNumber == 0",
      example: []string{
         "amc.mpd",
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "draken.mpd",
         "hulu.mpd",
         "itv.mpd",
         "kanopy.mpd",
         "max.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "pluto.mpd",
         "rakuten.mpd",
         "roku.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "SegmentTemplate.startNumber != nil",
      example: []string{
         "amc.mpd",
         "draken.mpd",
         "kanopy.mpd",
         "max.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "pluto.mpd",
         "roku.mpd",
      },
   },
   {
      code: "SegmentTemplate.startNumber == nil",
      example: []string{
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "hulu.mpd",
         "itv.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "rakuten.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "SegmentTemplate.timescale != nil",
      example: []string{
         "amc.mpd",
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "hulu.mpd",
         "itv.mpd",
         "kanopy.mpd",
         "max.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "pluto.mpd",
         "roku.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "SegmentTemplate.timescale == nil",
      example: []string{
         "draken.mpd",
         "rakuten.mpd",
      },
   },
   {
      code: "URL.IsAbs",
      example: []string{
         "amc.mpd",
         "hulu.mpd",
         "kanopy.mpd",
         "plex.mpd",
         "rakuten.mpd",
         "roku.mpd",
      },
   },
   {
      code: "URL.IsAbs == false",
      example: []string{
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "draken.mpd",
         "itv.mpd",
         "max.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "pluto.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: "len(MPD.Period) >= 2",
      example: []string{
         "max.mpd",
         "paramount.mpd",
      },
   },
   {
      code: "len(MPD.Period) == 1",
      example: []string{
         "amc.mpd",
         "canal.mpd",
         "cineMember.mpd",
         "criterion.mpd",
         "ctv.mpd",
         "draken.mpd",
         "hulu.mpd",
         "itv.mpd",
         "kanopy.mpd",
         "molotov.mpd",
         "mubi.mpd",
         "nbc.mpd",
         "plex.mpd",
         "pluto.mpd",
         "rakuten.mpd",
         "roku.mpd",
         "rtbf.mpd",
         "tubi.mpd",
      },
   },
   {
      code: `strings.Contains(SegmentTemplate.media, "$Number$")`,
      example: []string{
         "amc.mpd",
         "draken.mpd",
         "kanopy.mpd",
         "max.mpd",
         "molotov.mpd",
         "nbc.mpd",
         "paramount.mpd",
         "plex.mpd",
         "roku.mpd",
      },
   },
   {
      code: `strings.Contains(SegmentTemplate.media, "$Number%0")`,
      example: []string{
         "max.mpd",
         "pluto.mpd",
      },
   },
   {
      code: `strings.Contains(SegmentTemplate.media, "$Time$")`,
      example: []string{
         "canal.mpd",
         "cineMember.mpd",
         "ctv.mpd",
         "itv.mpd",
         "mubi.mpd",
         "rtbf.mpd",
      },
   },
}
